"use client";

import { useScriptStore } from "@/lib/store/script-store";
import { ScrollArea } from "@/components/ui/scroll-area";
import { SceneBlock } from "./scene-block";
import { TypewriterText } from "./typewriter-text";

export function ScreenplayViewer() {
  const { screenplay, streamingContent, isGenerating } = useScriptStore();

  if (!screenplay) {
    return (
      <div className="flex items-center justify-center h-64 text-muted-foreground">
        Belum ada naskah yang di-generate.
      </div>
    );
  }

  return (
    <ScrollArea className="h-[calc(100vh-200px)]">
      <div className="max-w-[700px] mx-auto p-8 bg-card rounded-lg border border-border font-screenplay text-sm leading-relaxed">
        <div className="text-center mb-8">
          <h1 className="text-lg font-bold uppercase tracking-widest">
            {screenplay.projectConfig.title}
          </h1>
          <p className="text-muted-foreground text-xs mt-2">
            Generated by DIMENSI LAIN SCRIPT PRODUCTION
          </p>
        </div>

        {screenplay.acts.map((act) => (
          <div key={act.actNumber} className="mb-8">
            <h2 className="text-center font-bold uppercase text-blood mb-4">
              ACT {act.actNumber}: {act.title}
            </h2>
            {act.scenes.map((scene) => (
              <SceneBlock key={scene.id} scene={scene} />
            ))}
          </div>
        ))}

        {isGenerating && streamingContent && (
          <div className="mt-4 pt-4 border-t border-border">
            <TypewriterText content={streamingContent} />
          </div>
        )}
      </div>
    </ScrollArea>
  );
}
